name: suite2p_bathellierlab
dependencies:
  - python>=3.7,<3.8
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - scikit-learn
  - pyqt
  - pip:
    - git+https://github.com/aprrenard/suite2p.git#egg=suite2p
    - rastermap>0.1.0
